wandb_version: 1

activation_1:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.7817146445387948
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718686220
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      - 61
      4: 3.10.13
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
